import { useEffect, useRef, useState } from 'react'
import { flushSync } from 'react-dom'
import amitGupteImage from './assets/amit-gupte.jpg'
import jayantAroraImage from './assets/jayant-arora.jpg'
import profileImage from './assets/profile.jpg'
import ryanParsellImage from './assets/ryan-parsell.jpg'
import steveRoweImage from './assets/steve-rowe.jpg'
import tomMereckisImage from './assets/tom-mereckis.jpg'
import varnithaSonnegowdaImage from './assets/varnitha-sonnegowda.jpg'
import vladGoncharovImage from './assets/vlad-goncharov.jpg'
import './App.css'
import SpatialField from './motion/SpatialField'
import SiteNav from './SiteNav'
import { revealRows } from './motion/rowReveal'
import { applyTheme, currentTheme, type Theme } from './motion/theme'
import { pageMeta, routes, type Page } from './pageMeta'

const resumeUrl = '/steven-wilssens-resume-2026.pdf'
const resumeFileName = 'Steven Wilssens Resume 2026.pdf'

type Entry = { role: string; company: string; dates: string; location: string; summary: string; points: string[] }

const experiences: Entry[] = [
  { role: 'Principal Group Product Manager - Windows & Devices Data', company: 'Microsoft', dates: 'Dec 2024 - Sep 2026', location: 'Redmond, Washington', summary: 'Led the PM team responsible for the data, insights, experimentation, and machine learning models that power decision-making across Windows and Devices.', points: ['Owned strategy and roadmap for data platform and insights products used by Windows engineers and PMs.', 'Led product managers driving experimentation, customer-signal analysis, and ML-powered insight products.', 'Partnered with engineering, data science, and research leadership across telemetry from more than a billion Windows devices.'] },
  { role: 'Principal Product Manager Lead - CSX Data', company: 'Microsoft', dates: 'Feb 2020 - Dec 2024', location: 'Redmond, Washington', summary: 'Built data products that told the story of the Windows customer experience and informed continuous improvement.', points: ['Wove customer signals and machine learning together to produce useful insights for Microsoft engineers.', 'Enabled data-supported decisions on hardware, software, and services quality.', 'Helped teams quickly detect and address issues affecting customer experiences.'] },
  { role: 'Principal Product Manager Lead - Azure DevOps', company: 'Microsoft', dates: 'Sep 2019 - Feb 2020', location: 'Redmond, Washington', summary: 'Defined new products, go-to-market strategies, and business decisions for the Azure DevOps Platform.', points: ['Increased market penetration through new product and business strategy.', 'Spearheaded rapid product analysis for a new product priority following GitHub’s acquisition.'] },
  { role: 'Principal Product Manager Lead - Silicon, Graphics, Media', company: 'Microsoft', dates: 'Jan 2018 - Sep 2019', location: 'Operating System Group · Redmond, Washington', summary: 'Led audio, spatial audio, game streaming, xCloud, Game DVR, broadcast, and casting initiatives.', points: ['Led the Microsoft Spatial Audio Platform across Windows, Xbox One, and new platforms.', 'Grew monthly active devices playing spatial audio by more than 250% over 1.5 years.', 'Worked with developers and data insights to identify and deliver essential spatial audio features.'] },
  { role: 'Principal Product Manager - Silicon, Graphics, Media', company: 'Microsoft', dates: 'Sep 2017 - Jan 2018', location: 'Operating System Group · Redmond, Washington', summary: 'Drove the Windows Sonic spatial audio platform for Windows and Xbox One while representing Microsoft at developer and game conferences.', points: ['Drove the launch of Dolby Access v3 and DTS Sound Unbound with new app services, licensing, and customization models.', 'Built partnerships with Surface, Store, Marketing, and Gaming to expand spatial audio to more endpoints and games.', 'Collaborated with Disney+ and Netflix to bring Dolby Atmos to Xbox and Windows.'] },
  { role: 'Senior Product Manager - Silicon, Graphics, Media', company: 'Microsoft', dates: 'Oct 2008 - Aug 2017', location: 'Operating Systems Group · Redmond, Washington', summary: 'Developed the Spatial Audio Platform, including Windows Sonic, for Windows and Xbox One.', points: ['Shipped platform technology spanning audio, media, and connected entertainment experiences.', 'Built the technical and partner foundation for a portfolio of spatial audio patents.'] },
  { role: 'Lead Developer and Team Lead', company: 'Compuware', dates: 'Jan 2005 - Dec 2006', location: 'Belgium', summary: 'Led a team of about 15 developers and the Project Support Office for Fluxys.', points: ['Owned hiring, evaluation, education, and job assignment for the development team.', 'Implemented a new development process and framework, coached developers and architects, and managed build infrastructure.', 'Presented application development and Visual Studio Team System practices to customers and developer communities.'] },
  { role: 'Software Developer', company: 'Cosmos', dates: 'Jan 2004 - Dec 2005', location: 'Antwerp Area, Belgium', summary: 'Built and supported software components across C# client and Java server systems using CORBA middleware.', points: ['Provided technical guidance, application redesigns, developer support, and code reviews.', 'Worked on the Technical Components team responsible for construction, maintenance, and support.'] },
  { role: 'Developer and Trainer', company: 'Info Support', dates: 'Jan 2001 - Dec 2004', location: 'Belgium', summary: 'Developed distributed .NET applications and trained teams across multiple organizations.', points: ['Led a development team at Agfa Gevaert and built C# and Visual Studio .NET applications for several clients.', 'Created scalable ADO.NET and SQL Server solutions and advised project and management teams on .NET architecture.', 'Delivered software development, architecture, and training work across the full delivery lifecycle.'] },
]

const patents = [['Spatializing audio data based on analysis of incoming audio data', 'US Patent 11,595,774 · Granted Feb 28, 2023 · Filed May 2017', 'https://patents.google.com/patent/US11595774B2/en'], ['Frame coding for spatial audio data', 'US Patent 10,535,355 · Granted Jan 14, 2020 · Filed May 2017', 'https://patents.google.com/patent/US10535355B2/en'], ['Personalization of spatial audio for streaming platforms', 'US Patent 10,469,975 · Granted Nov 5, 2019 · Filed May 2017', 'https://patents.google.com/patent/US10469975B2/en'], ['Shared three-dimensional audio bed', 'US Patent 10,419,866 · Granted Sep 17, 2019 · Filed Jun 2017', 'https://patents.google.com/patent/US10419866B2/en'], ['Adaptive audio rendering', 'US Patent 10,325,610 · Granted Jun 18, 2019 · Filed Jun 2016', 'https://patents.google.com/patent/US10325610B2/en'], ['Game streaming with spatial audio', 'US Patent 10,123,150 · Granted Nov 6, 2018 · Filed Jan 2017', 'https://patents.google.com/patent/US10123150B2/en'], ['Spatial audio resource management utilizing minimum resource working sets', 'US Patent 10,056,086 · Granted Aug 21, 2018 · Filed Jun 2017', 'https://patents.google.com/patent/US10056086B2/en'], ['Progressive streaming of spatial audio', 'Published application US 2018/0315437 · Published Nov 1, 2018', 'https://patents.google.com/patent/US20180315437A1/en'], ['Spectator audio and video repositioning', 'Published application US 2018/0220252 · Published Aug 2, 2018', 'https://patents.google.com/patent/US20180220252A1/en']]
const honors = [['Microsoft Lighthouse Award for Teamwork', 'Issued by Microsoft · Jan 2012'], ['Microsoft Compass Award for Individual Excellence', 'Issued by Microsoft · Jan 2011'], ['Microsoft Gold Star Award', 'Issued by Microsoft · Jan 2011'], ['Most Valuable Professional (MVP): VS Team System', 'Issued by Microsoft · Jan 2006']]
const news = [
  { title: 'All Xbox One consoles to get Dolby Atmos audio upmixing', publication: 'Alienware Arena', url: 'https://na.alienwarearena.com/ucf/show/1987916/boards/gaming-news/News/all-xbox-one-consoles-to-get-dolby-atmos-audio-upmixing', summary: 'Coverage of the Xbox Insider rollout that brought Dolby Atmos upmixing to Xbox One consoles, converting non-Atmos audio into a more immersive, object-based listening experience.', quote: '“There’ll be an option to toggle it off for those who want to hear non-Atmos audio in its original format.”' },
  { title: 'Xbox One And PC Getting Yet Another Cool New Audio Feature', publication: 'Forbes · John Archer', url: 'https://www.forbes.com/sites/johnarcher/2019/03/31/xbox-one-and-pc-getting-yet-another-cool-new-audio-feature/?', summary: 'A feature story about expanding spatial audio beyond encoded Atmos content, bringing a richer listening experience to Xbox One and PC games and media.', quote: 'Steven Wilssens is identified in the coverage as Xbox Audio Lead, helping shape the audio experience behind the feature.' },
  { title: 'DTS:X spatial surround sound coming to Windows 10 and Xbox One', publication: 'Windows Central', url: 'https://www.windowscentral.com/dtsx-spatial-surround-sound-coming-windows-10-xbox-one', summary: 'Coverage of DTS:X spatial surround sound coming to Windows 10 and Xbox One, part of the broader platform work to make immersive audio available across devices and content.', quote: 'Steven Wilssens is identified in the coverage as a leader of the spatial audio work bringing immersive sound to Windows and Xbox.' },
  { title: 'Spatial Audio with AudioGraph in UWP', publication: 'Microsoft Learn · Build 2016', url: 'https://learn.microsoft.com/en-us/shows/build-2016/p527', summary: 'A Build 2016 session focused on creating spatial audio experiences in Universal Windows Platform applications with AudioGraph.', quote: 'Steven Wilssens is associated with this early developer-facing work on spatial audio for Windows applications.' },
  { title: '“Throwing your voice” with Spatial Audio', publication: 'Windows Developer Blog', url: 'https://blogs.windows.com/windowsdeveloper/2016/09/15/throwing-your-voice-with-spatial-audio/', summary: 'A Windows developer story exploring how spatial audio can place a voice in a three-dimensional environment and make sound feel more present and directional.', quote: 'Steven Wilssens is associated with the Windows spatial-audio work discussed in this developer story.' },
]
const projects = [
  { name: 'Junior Track Cycling', url: 'https://juniortrackcycling.com', tag: 'Community project', summary: 'A project focused on making junior track cycling easier to discover, follow, and celebrate.' },
  { name: 'Leo Wilssens', url: 'https://leo.wilssens.com', tag: 'Family project', summary: 'A race journal and results site for Leo Wilssens, a junior track cyclist racing with Jerry Baker Juniors.' },
]
const capabilities = [
  ['01', 'Strategic leadership', 'Define and socialize long-term product vision, then translate it into roadmaps and decisions teams can execute against.'],
  ['02', 'Portfolio oversight', 'Manage consumer-facing surfaces and product portfolios, creating simple, consistent experiences across platforms.'],
  ['03', 'Build great PM teams', 'Hire, mentor, and grow high-performing PMs and people managers through clear craft standards and development paths.'],
  ['04', 'Executive communication', 'Align senior leaders on strategy, execution risks, and mitigation plans so complex initiatives stay clear and moving.'],
  ['05', 'Cross-functional alignment', 'Partner with Engineering, Design, Analytics, and Revenue leaders to balance business value with customer experience.'],
  ['06', 'Operational excellence', 'Establish rigorous experimentation and funnel-analysis frameworks that drive measurable gains in completion and retention.'],
  ['07', 'Technically grounded innovation', 'Bring technical depth, product judgment, and a builder’s instinct to ambiguous problems and turn signals into better decisions.'],
]
const recommendations = [
  ['Steve Rowe', 'Group Engineering Manager at Microsoft', `I had the privilege of working with Steven for five years. He was relentless in pursuing what he believed the product and our customers truly needed, even when it wasn’t the prevailing trend. Always full of ideas, he continually identified new features and opportunities to create customer value. Steven was also a quick study who could enter an unfamiliar space, rapidly develop a strong understanding of it, and begin generating thoughtful ideas.

Steven’s straightforward style made working with him refreshingly simple: he said what he meant, meant what he said, and readily changed his mind when presented with better ideas. He built strong connections quickly and consistently found the right people to help move work forward. As a leader, he had a clear vision for his team, cared deeply about his people, and invested significant time and energy in their growth and development.`],
  ['Varnitha Sonnegowda', 'Senior Program Manager at Microsoft | Windows Data Decision Intelligence R&D', `I had the privilege of reporting to Steven for over six years, during which time he grew into a Group Product Manager role. Throughout that journey, Steven consistently stood out as one of the most impactful leaders I've worked with.

What sets Steven apart is his rare combination of strategic thinking, product intuition, and willingness to dive deep into the details. He has an exceptional ability to connect customer needs with business outcomes and translate complex problems into clear, actionable plans. Whether driving a new initiative, navigating ambiguity, or helping teams align around a common vision, Steven brings clarity, focus, and momentum.

Steven is also a truly hands-on leader. He never hesitates to roll up his sleeves, challenge assumptions, and work alongside the team to solve difficult problems. His technical depth, product judgment, and bias for action enable him to quickly identify root causes and guide teams toward pragmatic, high-impact solutions.

Beyond his business and technical strengths, Steven is deeply invested in the growth and success of the people around him. He actively creates opportunities for others, advocates for their work, and ensures contributions are recognized. Many of the opportunities I've had in my career can be traced back to Steven's mentorship, trust, and willingness to help others grow. He is also a champion of diversity and inclusion. As I transitioned back to work after maternity leave as a mother of two, Steven's support, flexibility, and encouragement helped me navigate that transition with confidence and continue growing in my career.

I'm grateful for the guidance and support Steven has provided over the years, and I would highly recommend him to any organization looking for a leader who can build strong teams, deliver meaningful business impact, and inspire people to do their best work. Any organization would benefit immensely from Steven's product acumen, leadership, and unwavering commitment to people and results.`],
  ['Ryan Parsell', 'Principal Software Engineering Manager', `Steven has been one of my favorite people to brainstorm with and I'm already missing his intellectual partnership. We met weekly, working together on experimentation, AI, and plenty of hard problems. Steven is one of the people you want in the room when the answer isn't obvious. He’s curious, forward-thinking, and genuinely willing to explore unconventional ideas and approaches rather than immediately shut them down. When working on tough engineering and data science problems, Steven was a champion of not letting perfect be the enemy of good.

Steven brought his deep technical and software engineering experience to the art of product management. And to an extent kept working as a software engineer. Steven completed some large AI projects that even after his departure are having significant impact here.

I really enjoyed working with him and would happily do it again.`],
  ['Vlad Goncharov', 'Senior Software Engineer at Microsoft', `I had the pleasure of working with Steven Wilssens for approximately six years at Microsoft, including during his tenure as Group Product Manager on our team. We collaborated on several significant projects, and I developed a strong appreciation for his judgment, professionalism, and approach to product leadership.

What impressed me most was Steven’s ability to examine an existing product and quickly recognize where it could better serve customers. He brought a clear vision for how a product should evolve, with customer needs consistently guiding his priorities. His recommendations reflected careful consideration of what needed to change and why that change would matter.

Steven was also an excellent communicator. He expressed his ideas with precision and made the reasoning behind his proposals easy to follow. I particularly valued the clarity he brought to our discussions, which helped us work through complex questions and establish a shared understanding of our objectives.

I recommend Steven with confidence for senior product leadership roles. He combines strong product instincts with the ability to articulate a compelling direction, and I would be glad to work with him again.`],
  ['Omari Carter-Thorpe', 'Senior Software Engineer at Microsoft', `I worked with Steven for roughly six years—four while he was a Principal PM Lead and two while he was the Group Product Manager for our PM and SWE team.

Steven is particularly strong at finding a path forward when the obvious approach isn't available. He looks at problems from different angles, identifies alternative routes to the end goal, and is pragmatic about what it takes to get there. He also has a strong ability to build relationships across the broader Windows organization and turn those relationships into productive partnerships—helping teams align, bring the right people together, and move work forward.

He navigates well at different levels of detail. While much of his role has him operating at the broader level of strategy and direction, when the situation calls for it he is equally effective getting into the details, understanding the realities on the ground, and working through complex situations with the team.

Steven is a strong partner and an effective leader. He is particularly good at communicating strategy in writing, bringing clarity to direction, decisions, and priorities and helping teams understand not just where they are going, but why.

I valued the opportunity to work with Steven over those six years and would welcome the opportunity to work with him again.`],
  ['Tom Mereckis', 'Data and AI Leader', `I fully recommend Steven as a great technology, product, and team leader. We worked together for a half decade on the Windows data team, partnering on numerous critical and complex projects. I always found him to be technically deep, able to learn more very quickly, able to apply what he knows to uncertain situations, and an effective leader of both his own people but also others around him. He always works and collaborates with great energy, and always seeks to do the right things. Together we delivered numerous impactful data products and systems for Windows for both customers and internal use. I'd work with him again anytime, anywhere, on anything.`],
  ['Amit Gupte', 'Senior Technical Program Manager - Data & AI Platform at Microsoft', `Steven was a trusted mentor to me for three years and my skip-level manager for two. He pairs a deep commitment to product excellence with a true builder’s mindset, having established the critical data products and rhythms that measured and elevated Windows quality across preview channels and retail scale. His intuitive understanding of customer behavior was second to none, notably demonstrated when he accurately forecast how a key Windows AI feature would land in retail well before broad rollout.

He leads by building rather than just delegating. When a retiring OKR management tool created an operational vacuum, Steven partnered with me to ideate and rapidly stand up a functional replacement from scratch, showing his understanding of modern AI SDLC.

Beyond his strategic acumen, Steven is a dedicated people champion. He was an invaluable sounding board for tough problems, continually advocated for my work, and made sure my work had the right visibility. Any organization would benefit immensely from his vision, energy, and leadership.`],
  ['Jayant Arora', 'Product at Microsoft | AI Product Management', `I’ve had the opportunity to work with Steven for several years, first as my manager and later as my skip-level manager. Throughout that time, he has been one of the most impactful leaders and coaches in my career.

What sets Steven apart is his combination of strong product leadership, technical aptitude, and genuine investment in his team. He leads from a strategic level and gives his team the space to own their work but never shies away from getting into the details when needed. Whether it’s understanding a complex technical problem, working through ambiguity, or helping unblock a difficult initiative, Steven has always been willing to get his hands dirty and help the team find a path forward.

He has led the team through multiple successful projects and consistently demonstrated the grit needed to drive large initiatives forward. His attention to detail, problem-solving ability, and commitment to transparency create an environment where teams can execute with clarity and confidence. He is also someone who will advocate strongly for his people and make sure their contributions are seen.

One of Steven’s greatest strengths is his ability to create opportunities for his team. He actively finds ways for people to grow, represents their work effectively, and ensures they get the visibility and recognition they deserve.

I’m incredibly grateful for the coaching, trust, and opportunities Steven has given me over the years. His leadership has shaped how I approach problems, think about products, and navigate my own career. He is the kind of leader who can see the bigger picture, understand the technical details when it matters, and bring his team along with him.`],
]
// Short verbatim excerpts from the recommendations, shown on the home page.
const pullQuotes = [
  ['Ryan Parsell', 'Steven is one of the people you want in the room when the answer isn’t obvious.'],
  ['Amit Gupte', 'He leads by building rather than just delegating.'],
  ['Tom Mereckis', 'I’d work with him again anytime, anywhere, on anything.'],
]

const education = { degree: 'Bachelor’s degree, Computer Science', school: 'Karel de Grote, Belgium', dates: '2000 - 2004' }
const languages = 'Dutch and English (native), French (intermediate)'

const recommendationLinks: Record<string, string> = {
  'Steve Rowe': 'https://www.linkedin.com/in/steverowe/?skipRedirect=true',
  'Varnitha Sonnegowda': 'https://www.linkedin.com/in/varnitha/?skipRedirect=true',
  'Ryan Parsell': 'https://www.linkedin.com/in/ryanparsell/?skipRedirect=true',
  'Vlad Goncharov': 'https://www.linkedin.com/in/vlad-goncharov/?skipRedirect=true',
  'Omari Carter-Thorpe': 'https://www.linkedin.com/in/omari-carter-thorpe-b46078159/',
  'Tom Mereckis': 'https://www.linkedin.com/in/tom-mereckis-6651562/?skipRedirect=true',
  'Amit Gupte': 'https://www.linkedin.com/in/amit-gupte/?skipRedirect=true',
  'Jayant Arora': 'https://www.linkedin.com/in/arorajayant/',
}
const recommendationImages: Record<string, string> = {
  'Steve Rowe': steveRoweImage,
  'Varnitha Sonnegowda': varnithaSonnegowdaImage,
  'Ryan Parsell': ryanParsellImage,
  'Vlad Goncharov': vladGoncharovImage,
  'Tom Mereckis': tomMereckisImage,
  'Amit Gupte': amitGupteImage,
  'Jayant Arora': jayantAroraImage,
}

const pageFromLocation = (): Page => { const path = window.location.pathname.replace(/^\/+|\/+$/g, '').replace(/\.html$/, ''); if (path === '' || path === 'index') return 'home'; return (routes as readonly string[]).includes(path) ? path as Page : 'notFound' }

function App() {
  const [page, setPage] = useState<Page>(pageFromLocation)
  const [expandedRecommendation, setExpandedRecommendation] = useState<string | null>(null)
  const [selectedExperience, setSelectedExperience] = useState(0)
  const experienceRefs = useRef<Array<HTMLElement | null>>([])
  const graphScrollRef = useRef<HTMLDivElement>(null)
  const scrollLockUntil = useRef(0)
  const [theme, setTheme] = useState<Theme>(() => (typeof document === 'undefined' ? 'light' : currentTheme()))
  const toggleTheme = () => { const next: Theme = theme === 'dark' ? 'light' : 'dark'; const swap = () => flushSync(() => { applyTheme(next); setTheme(next) }); if (document.startViewTransition && !window.matchMedia?.('(prefers-reduced-motion: reduce)').matches) document.startViewTransition(swap); else swap() }
  // Highlight the role being read and keep its node in view on the graph.
  useEffect(() => { if (page !== 'experience' || !('IntersectionObserver' in window)) return; const observer = new IntersectionObserver((entries) => { if (Date.now() < scrollLockUntil.current) return; const entry = entries.find((item) => item.isIntersecting); const index = entry ? experienceRefs.current.indexOf(entry.target as HTMLElement) : -1; if (index >= 0) setSelectedExperience(index) }, { rootMargin: '-35% 0px -55% 0px' }); experienceRefs.current.forEach((element) => element && observer.observe(element)); return () => observer.disconnect() }, [page])
  useEffect(() => { const scroller = graphScrollRef.current; const node = scroller?.querySelectorAll<HTMLElement>('.graph-node')[selectedExperience]; if (scroller && node) scroller.scrollTo?.({ left: node.offsetLeft - scroller.clientWidth / 2 + node.offsetWidth / 2, behavior: 'smooth' }) }, [selectedExperience])
  useEffect(() => revealRows(), [page])
  useEffect(() => { const syncPage = () => setPage(pageFromLocation()); window.addEventListener('popstate', syncPage); return () => window.removeEventListener('popstate', syncPage) }, [])
  useEffect(() => { document.title = pageMeta[page].title; document.querySelector('meta[name="description"]')?.setAttribute('content', pageMeta[page].description) }, [page])
  const navItems: [Page, string][] = [['about', 'About'], ['experience', 'Experience'], ['recommendations', 'Recommendations'], ['patents', 'Patents'], ['honors', 'Honors'], ['news', 'In the News'], ['projects', 'Projects']]
  const renderResumeLink = (className: string) => <a className={className} href={resumeUrl} download={resumeFileName}>Download resume ↓</a>
  const renderPageHeader = ({ title, intro, showResume = false }: { title: string; intro: string; showResume?: boolean }) => <div className="page-heading"><a className="back-link" href="/">← Profile</a><h1>{title}</h1><p>{intro}</p>{showResume && renderResumeLink('primary-button')}</div>
  const renderImpactStrip = () => <section className="impact-strip" aria-label="Selected impact"><div><strong>250%+</strong><span>growth in monthly active spatial-audio devices</span></div><div><strong>1B+</strong><span>Windows devices informing product decisions</span></div><div><strong>15%</strong><span>increase in Windows adoption</span></div><div><strong>30%</strong><span>reduction in customer issues</span></div></section>
  const renderCapabilities = () => <section className="capabilities"><div className="capabilities-heading"><span className="eyebrow">What I do well</span><h2>Leadership that turns ambiguity into momentum.</h2></div><div className="capability-grid">{capabilities.map(([number, title, description]) => <article key={title}><span className="section-number">{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
  const renderPullQuotes = () => <section className="pull-quotes" aria-label="What colleagues say"><span className="eyebrow">What colleagues say</span><div className="pull-quote-grid">{pullQuotes.map(([name, quote]) => { const role = recommendations.find(([person]) => person === name)?.[1]; return <figure key={name}><blockquote>“{quote}”</blockquote><figcaption><span className="avatar">{recommendationImages[name] ? <img src={recommendationImages[name]} alt="" /> : name.split(' ').map((part) => part[0]).join('')}</span><span><strong>{name}</strong><small>{role}</small></span></figcaption></figure> })}</div><a className="text-link" href="/recommendations">Read all {recommendations.length} recommendations →</a></section>
  const renderContactBand = () => <section className="contact-band"><div><span className="eyebrow">Start a conversation</span><h2>Working through a hard product problem?</h2><p>I’m exploring product leadership, experimentation, audio, data, and AI.</p></div><div className="contact-actions"><a className="primary-button" href="mailto:steven@wilssens.com">Email Steven ↗</a>{renderResumeLink('text-link')}<a className="text-link" href="https://www.linkedin.com/in/steven-wilssens-59495889/" target="_blank" rel="noreferrer">Connect on LinkedIn ↗</a></div></section>
  const renderHome = () => <><section className="profile-hero"><SpatialField><img src={profileImage} alt="Steven Wilssens" /></SpatialField><div className="hero-copy"><p className="eyebrow">Steven Wilssens · Seattle area</p><h1>Product leadership for the next chapter.</h1><p className="lede">I lead with strategy, clarity, and a builder’s instinct: turning ambiguous problems into decisions, roadmaps, and teams that move.</p><div className="hero-actions"><a className="primary-button" href="/experience">View experience</a>{renderResumeLink('text-link')}<a className="text-link" href="mailto:steven@wilssens.com">steven@wilssens.com ↗</a><a className="text-link" href="https://www.linkedin.com/in/steven-wilssens-59495889/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div><div className="hero-facts"><span>Independent product leader</span><span>Strategy · Portfolio · Teams</span><span>Clarity · Rigor · Momentum</span></div></section><section className="overview-grid"><article><span className="section-number">01</span><h2>About</h2><p>Product, portfolio, and people leadership grounded in customer insight, rigorous execution, and technical judgment.</p><a href="/about">Read the story →</a></article><article><span className="section-number">02</span><h2>Experience</h2><p>From Belgian software development to Windows data, spatial audio, Azure DevOps, and team leadership.</p><a href="/experience">See the timeline →</a></article><article><span className="section-number">03</span><h2>Proof of work</h2><p>Patents, honors, recommendations, press coverage, and projects from the work I have helped bring into the world.</p><div className="proof-links"><a href="/patents">Patents</a><a href="/honors">Honors</a><a href="/recommendations">Recommendations</a><a href="/news">In the News</a><a href="/projects">Projects</a></div></article></section></>
  const renderAbout = () => <>{renderPageHeader({ title: 'About', intro: 'A product and technology leader beginning a new chapter after Microsoft.' })}<section className="reading-layout"><div className="reading-main"><p className="intro-paragraph">After more than a decade at Microsoft, I am now bringing a career in data, AI, product strategy, software, and people leadership into its next chapter.</p><p>Most recently, I led the Windows & Devices Data PM team, advancing the Windows ecosystem through data-driven strategies. I care about the space where customer signals, experimentation, machine learning, and strong product judgment meet.</p><p>Before leading Windows data teams, I built products and platforms across Azure DevOps, spatial audio, game streaming, and operating systems. Earlier still, I was a developer and team lead in Belgium, where I learned to pair technical depth with practical delivery and the growth of the people around me.</p></div><aside className="side-note"><span>Most recently</span><strong>Principal Group Product Manager, Microsoft</strong><span>Now exploring</span><strong>Product leadership, experimentation, audio, data, and AI</strong><span>Education</span><strong>{education.degree}, {education.school}</strong><span>Languages</span><strong>{languages}</strong></aside></section></>
  const renderExperience = () => <>{renderPageHeader({ title: 'Experience', intro: 'A full career moving between code, customers, strategy, and teams.', showResume: true })}<section className="experience-graph" aria-label="Interactive experience timeline"><div className="graph-scroll" ref={graphScrollRef}><div className="graph-track" style={{ '--progress': selectedExperience } as React.CSSProperties}>{experiences.map((item, index) => <button className={`graph-node ${selectedExperience === index ? 'selected' : ''}`} style={{ '--node-index': index } as React.CSSProperties} type="button" key={`${item.role}-${item.dates}`} onClick={() => { scrollLockUntil.current = Date.now() + 1000; setSelectedExperience(index); experienceRefs.current[index]?.scrollIntoView?.({ behavior: 'smooth', block: 'start' }) }} aria-label={`Scroll to ${item.role} at ${item.company}`} aria-pressed={selectedExperience === index}><span className="graph-dot" /><span className="graph-year">{item.dates.match(/\d{4}/)?.[0]}</span><span className="graph-role" title={item.role}>{item.role}</span><span className="graph-company">{item.company}</span></button>)}</div></div></section><section className="timeline">{experiences.map((item, index) => <article className="timeline-item" ref={(element) => { experienceRefs.current[index] = element }} key={`${item.role}-${item.dates}`}><div className="timeline-date">{item.dates}</div><div className="timeline-body"><span className="company-label">{item.company}</span><h2>{item.role}</h2><p className="muted">{item.location}</p><p>{item.summary}</p><ul>{item.points.map((point) => <li key={point}>{point}</li>)}</ul></div></article>)}<article className="timeline-item"><div className="timeline-date">{education.dates}</div><div className="timeline-body"><span className="company-label">Education</span><h2>{education.degree}</h2><p className="muted">{education.school}</p><p>Languages: {languages}.</p></div></article></section></>
  const renderRecommendations = () => <>{renderPageHeader({ title: 'Recommendations', intro: 'A few notes from people who have built products and teams with me.' })}<section className="recommendation-list">{recommendations.map(([name, role, text]) => { const isExpanded = expandedRecommendation === name; return <article className="recommendation" key={name}><div className="avatar">{recommendationImages[name] ? <img src={recommendationImages[name]} alt={`${name} profile`} /> : name.split(' ').map((part) => part[0]).join('')}</div><div><h2><a className="recommendation-author" href={recommendationLinks[name]} target="_blank" rel="noreferrer">{name} ↗</a></h2><p className="muted">{role}</p><blockquote className={isExpanded ? 'expanded' : ''}>“{text}”</blockquote><button className="more-button" type="button" onClick={() => setExpandedRecommendation(isExpanded ? null : name)} aria-expanded={isExpanded}>{isExpanded ? 'less' : 'more'}</button></div></article> })}</section></>
  const renderArchive = ({ title, intro, items, kind }: { title: string; intro: string; items: string[][]; kind: 'patent' | 'honor' }) => <>{renderPageHeader({ title, intro })}<section className={`archive-list ${kind}`}>{items.map(([name, meta, url], index) => <article key={name}><span className="archive-index">{String(index + 1).padStart(2, '0')}</span><div><h2>{name}</h2><p>{meta}</p>{kind === 'patent' && url && <a href={url} target="_blank" rel="noreferrer">View on Google Patents ↗</a>}</div></article>)}</section></>
  const renderNews = () => <>{renderPageHeader({ title: 'In the News', intro: 'Coverage of spatial audio work from the Windows and Xbox era.' })}<section className="archive-list news-list">{news.map((item, index) => <article key={item.title}><span className="archive-index">{String(index + 1).padStart(2, '0')}</span><div><p className="news-publication">{item.publication}</p><h2>{item.title}</h2><p className="news-summary">{item.summary}</p><blockquote className="news-quote">{item.quote}<cite>Steven Wilssens · {item.publication}</cite></blockquote><a href={item.url} target="_blank" rel="noreferrer">Read article ↗</a></div></article>)}</section></>
  const renderProjects = () => <>{renderPageHeader({ title: 'Projects & interests', intro: 'A few projects where product thinking meets family, community, and the joy of making things useful.' })}<section className="project-grid">{projects.map((project) => <article className="project-card" key={project.name}><p className="project-tag">{project.tag}</p><h2>{project.name}</h2><p>{project.summary}</p><a href={project.url} target="_blank" rel="noreferrer">Visit project ↗</a></article>)}</section></>

  const renderNotFound = () => <>{renderPageHeader({ title: 'Page not found', intro: 'That page does not exist or has moved. Try the profile, the experience timeline, or the resume.', showResume: true })}</>

  return <div className="site-shell"><header className="site-header"><a className="wordmark" href="/">steven<span>.</span>wilssens</a><SiteNav items={navItems} page={page} /><div className="header-contact"><button className="theme-toggle" type="button" onClick={toggleTheme} aria-label={theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'} title={theme === 'dark' ? 'Light mode' : 'Dark mode'}>{theme === 'dark' ? <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4.5" /><path d="M12 2.5v2.5M12 19v2.5M2.5 12H5M19 12h2.5M5.3 5.3l1.8 1.8M16.9 16.9l1.8 1.8M5.3 18.7l1.8-1.8M16.9 7.1l1.8-1.8" /></svg> : <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 14.5A8.5 8.5 0 0 1 9.5 4a8.5 8.5 0 1 0 10.5 10.5Z" /></svg>}</button>{renderResumeLink('text-link')}<a className="primary-button" href="mailto:steven@wilssens.com">Email ↗</a></div></header><main>{page === 'home' && <>{renderHome()}{renderPullQuotes()}{renderCapabilities()}{renderImpactStrip()}{renderContactBand()}</>}{page === 'about' && renderAbout()}{page === 'experience' && renderExperience()}{page === 'recommendations' && renderRecommendations()}{page === 'patents' && renderArchive({ title: 'Patents', intro: 'Seven granted US patents in spatial audio, streaming, and media, all assigned to Microsoft.', items: patents, kind: 'patent' })}{page === 'honors' && renderArchive({ title: 'Honors & awards', intro: 'Recognition for teamwork, individual excellence, and a long practice of building useful things.', items: honors, kind: 'honor' })}{page === 'news' && renderNews()}{page === 'projects' && renderProjects()}{page === 'notFound' && renderNotFound()}</main><footer><span>Steven Wilssens · 2026</span><span><a href="https://www.linkedin.com/in/steven-wilssens-59495889/" target="_blank" rel="noreferrer">LinkedIn</a> · <a href={resumeUrl} download={resumeFileName}>Resume</a> · steven@wilssens.com</span></footer></div>
}

export default App
